### ISSUE TITLE
sharing the css for the photo gallery?

### ISSUE THREAD

**Issue by Kdreval** [baptiste/quarto-gallery#1]
Hi @baptiste !

Was looking at your photo gallery and trying to make a similar grid to what you have here: https://p.bapt.xyz/vancouver/ or any other page at the gallery :smile: 
I tried to create a similar layout but stuck with images being disorganized and not centered below the main first picture like in your gallery. I thought it might be because all images are different sizes but it looks like you have the photos in different sizes as well. 
I looked at your bog post [here](https://b.bapt.xyz/posts/gallery/#generating-the-page-with-quarto) (thanks for sharing!) and tried that css chunk but still have disorganized images not replicating the layout from the gallery. I found this repo and tried the [style.css](https://github.com/baptiste/quarto-gallery/blob/main/style.css) but again no luck. 
I wonder if maybe the current gallery has an updated css that you can share?

**Comment by baptiste** [comment]
@Kdreval I seem to have messed up the quarto publish settings in this repo, so I'll delete it and create a new one from scratch. I'll send you an email when it works (ping me after Xmas if I forget)
